services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: smart-crop-postgres
    environment:
      POSTGRES_DB: smart_crop
      POSTGRES_USER: smartcrop
      POSTGRES_PASSWORD: smartcrop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: